### PR TITLE
Bug 1897769 - Add microsurvey badges to completed experiments

### PR DESCRIPTION
**Pull request by sarahhjchung**
[Bug 1897769](https://bugzilla.mozilla.org/show_bug.cgi?id=1897769)

Microsurvey badges were missing in https://github.com/mozilla/skylight/pull/358 so adding it here!

### CODE REVIEW

**Review by AllegroFox — APPROVED** [review]
Awesome, thank you!

**Comment by dmose** [comment]
How about adding a test?

**Comment by dmose** [comment]
(This might be hard to notice if it regressed)

**Comment by sarahhjchung** [comment]
@dmose I added tests in the other PR to check that the Microsurvey badge is displayed in the correct cases inside MessageTable. Do you mean to add a test that it correctly shows up specifically in the `/complete` page?

**Comment by dmose** [comment]
@sarahhjchung yes

**Comment by dmose** [comment]
(Since the existing tests didn't catch it)

**Review by dmose — APPROVED** [review]
LGTM; r=dmose

**Pull request merged**
