### PR TITLE
Bug 1906937 - Display inline impressions data 

### PR DESCRIPTION
**Pull request by sarahhjchung**
[**Bug 1906937**](https://bugzilla.mozilla.org/show_bug.cgi?id=1906937)

Changes made:
- Code
    - Updated `getCTRPercent` to also return impressions data
    - Metrics columns now display impressions data with the CTR percents

Note:
- This is the first iteration of the inline impressions data and I'm open to suggestions on how to style this info differently

### CODE REVIEW

**Comment by dmose** [comment]
> The CTR and User Profiles Impressed tile is updated with a new Impressions calculation (see [infobar](https://mozilla.cloud.looker.com/dashboards/1829) and [message performance](https://mozilla.cloud.looker.com/dashboards/1835) dashboards)

Why did these need to change? This was already being used to compute the CTR and already being displayed in the tile, I thought.

> This is the first iteration of the inline impressions data and I'm open to suggestions on how to style this info differently

* I wonder if the whole CTR/Impressions section should be a single link with a single offsite icon (assuming there's a reasonable way to make this look visually clean and understandable)

**Comment by sarahhjchung** [comment]
Yes, that's right. I changed it back to use the existing dashboards and got impression data from the original tiles. 

Also, I made the CTR/impression metrics to be in one line and abbreviated "Impressions" to "Impr"

**Review by dmose — APPROVED** [review]
r=dmose on the code; it looks great.  I have a couple of thoughts on the visuals:

* "Impr." seems like it is likely to make it harder to skim
* "12.35% CTR" reads like prose, and "Impr.: 5,200" reads like an entry from a text table.
* If we got from "Impr." to "Impressions" in the same line that makes things pretty wide (or else squished, depending on window size).

So the upshot is that my gut is to go for something along the lines of:

12.35% CTR
5,200 impressions

all as a single link, despite being split across two lines.

I don't love it, and I'm open to other options. I'll leave the final choice up to you.

**Comment by sarahhjchung** [comment]
> 
> 12.35% CTR 
> 5,200 impressions
> 
I was playing around with the styling and I like that idea the most right now. I'll merge this PR and I think we can always re-iterate on the styling in a future ticket if needed.

**Pull request merged**
